# Generated by Django 3.0.4 on 2020-04-09 20:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import drf_mtg_card_crawler.enums
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('retries', models.IntegerField(default=0)),
                ('status', enumfields.fields.EnumField(db_index=True, default='queued', enum=drf_mtg_card_crawler.enums.SearchStatus, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(db_index=True, max_length=250, unique=True)),
                ('website', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(db_index=True, max_length=150)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='drf_mtg_card_crawler.Search')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=250)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('expires', models.DateTimeField()),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_mtg_card_crawler.Store')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='drf_mtg_card_crawler.SearchTerm')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='search',
            name='stores',
            field=models.ManyToManyField(to='drf_mtg_card_crawler.Store'),
        ),
    ]
