# Generated by Django 3.0.4 on 2020-08-07 19:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_mtg_card_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='exceptions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list, null=True, size=None),
        ),
    ]
