# Generated by Django 3.0.4 on 2021-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_mtg_card_crawler', '0002_search_exceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
