# Generated by Django 3.0.4 on 2021-04-11 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drf_mtg_card_crawler', '0003_store_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('error', models.CharField(max_length=250)),
                ('expires', models.DateTimeField()),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_mtg_card_crawler.Store')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='drf_mtg_card_crawler.SearchTerm')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
