# Generated by Django 3.0.4 on 2021-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_mtg_card_crawler', '0004_searcherror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
