# Generated by Django 3.1.8 on 2021-04-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='metadata',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
