# Generated by Django 3.1.8 on 2021-04-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummage', '0002_auto_20210413_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='image',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
