# Generated by Django 3.1.8 on 2021-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummage', '0003_auto_20210414_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
