# Generated by Django 3.1.8 on 2021-06-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummage', '0004_auto_20210415_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='metadata',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='price',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
