# Generated by Django 3.0.4 on 2020-04-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_mtg_card_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='cachable',
            field=models.BooleanField(default=True),
        ),
    ]
