# Generated by Django 3.0.4 on 2020-04-01 16:38

from django.db import migrations, models
import drf_mtg_card_crawler.enums
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drf_mtg_card_crawler', '0002_searchresult_cachable'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='status',
            field=enumfields.fields.EnumField(db_index=True, default='queued', enum=drf_mtg_card_crawler.enums.SearchStatus, max_length=50),
        ),
    ]
